#!/usr/bin/env bash

set -e

readonly DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd ${DIR} > /dev/null

printAddedToPathAndExit() {
  echo "bytes added to PATH."
  echo "You may need to restart your Terminal for changes to become effective."
  exit 0
}

install() {
  local bashProfile
  if [ -n "$(uname -s | grep Linux)" ]; then
    bashProfile=~/.bashrc
  elif [ -n "$(uname -s | grep Darwin)" ]; then
    bashProfile=~/.bash_profile
  else
    echo "Unknown platform. In order to install bytes add $DIR/bin to your PATH."
    exit 1
  fi

  if [ -e "${bashProfile}.local" ]; then
    bashProfile=$bashProfile.local
  fi

  if [ $(command -v bytes >/dev/null 2>&1) ]; then
    printAddedToPathAndExit
  else
    echo "" >> ${bashProfile}
    echo "# Setting PATH for bytes" >> ${bashProfile}
    echo "PATH=\"${DIR}/bin:\${PATH}\"" >> ${bashProfile}
    echo "export PATH" >> ${bashProfile}
    printAddedToPathAndExit
  fi
}

install

popd > /dev/null
